#!/bin/bash

# Quick Installation Commands
# Copy and paste these commands one by one

echo "========================================"
echo "XSAMI Frontend - Quick Install Commands"
echo "========================================"
echo ""

# Option 1: Automated Setup (Recommended)
echo "OPTION 1: Automated Setup (Recommended)"
echo "========================================"
echo ""
echo "cd /home/husain/XSAMI/xsami-front && ./setup-node.sh"
echo ""
echo "This will:"
echo "  - Guide you through Node.js installation"
echo "  - Install all dependencies"
echo "  - Verify everything works"
echo ""
echo "---"
echo ""

# Option 2: Manual Setup
echo "OPTION 2: Manual Setup"
echo "========================================"
echo ""
echo "# Install Node.js using nvm (Recommended):"
echo "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash"
echo "source ~/.bashrc"
echo "nvm install 20"
echo "nvm use 20"
echo ""
echo "# OR using apt (Simple):"
echo "sudo apt update && sudo apt install -y nodejs npm"
echo ""
echo "# Then install dependencies:"
echo "cd /home/husain/XSAMI/xsami-front"
echo "npm install"
echo ""
echo "# Start development server:"
echo "npm run dev"
echo ""
echo "---"
echo ""

# Option 3: Quick One-Liner
echo "OPTION 3: Quick One-Liner (nvm method)"
echo "========================================"
echo ""
echo "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && source ~/.bashrc && nvm install 20 && nvm use 20 && cd /home/husain/XSAMI/xsami-front && npm install && npm run dev"
echo ""
echo "---"
echo ""

# Verification Commands
echo "VERIFICATION COMMANDS"
echo "========================================"
echo ""
echo "# Check Node.js:"
echo "node --version"
echo ""
echo "# Check npm:"
echo "npm --version"
echo ""
echo "# Check TypeScript (after npm install):"
echo "cd /home/husain/XSAMI/xsami-front && npx tsc --noEmit"
echo ""
echo "---"
echo ""

# Troubleshooting
echo "TROUBLESHOOTING"
echo "========================================"
echo ""
echo "# If npm not found after installing Node.js:"
echo "source ~/.bashrc"
echo ""
echo "# If permission errors:"
echo "mkdir ~/.npm-global"
echo "npm config set prefix '~/.npm-global'"
echo "echo 'export PATH=~/.npm-global/bin:\$PATH' >> ~/.bashrc"
echo "source ~/.bashrc"
echo ""
echo "# Clean reinstall:"
echo "cd /home/husain/XSAMI/xsami-front"
echo "rm -rf node_modules package-lock.json"
echo "npm cache clean --force"
echo "npm install"
echo ""
echo "---"
echo ""

echo "Choose an option above and run the commands!"
echo ""
